### ISSUE TITLE
[BUG] QuickShop sending blank line when translate message set to empty string

### ISSUE THREAD

**Issue by Baktus79** [Ghost-chu/QuickShop-Hikari#1583]
### Description

I'm not sure if this is defined as a bug or not, but the `ShopPreCreateEvent` event is fired after checking chests for double chests. This means that players will get error messages saying that double chests are not possible.

![Skjermbilde_2024-05-25_234856](https://github.com/Ghost-chu/QuickShop-Hikari/assets/19745447/bbed4817-8a3a-4f2e-8463-151a642c3f85)

### Steps to reproduce

```java
@EventHandler
public void onShopPreCreate(ShopPreCreateEvent e) {
	if (DataManager.disabledCreate.contains(e.getCreator().getUniqueId())) {
		e.setCancelled(true, "ShopCreate disabled by user.");
	}
}
```

### Expected Behaviour

For me, it is natural to believe that all operations dealing with pre shop creations will fire the `ShopPreCreateEvent`, and as such could cancel out all triggers that affect the creation of a shop.

### Screenshots

Image shows that the message "You cannot create a double chest shop." is still displayed even if the event is cancelled.

![Skjermbilde_2024-05-25_234856](https://github.com/Ghost-chu/QuickShop-Hikari/assets/19745447/e3c29b6f-cb85-47a0-b2f1-a0d66202daf7)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FzKnDVmexYN

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Hikari/blob/51488e60622a91792a3abbc232c8a5e12c18656a/quickshop-bukkit/src/main/java/com/ghostchu/quickshop/listener/PlayerListener.java#L281

https://github.com/Ghost-chu/QuickShop-Hikari/blob/51488e60622a91792a3abbc232c8a5e12c18656a/quickshop-bukkit/src/main/java/com/ghostchu/quickshop/listener/PlayerListener.java#L326

The ShopPreCreateEvent exists for the sole purpose of allowing the store creation query to be hidden for the player if the store creation conditions are met.
ShopCreateEvent should also be listened to if store creation is to be blocked.

When the player does not fulfill the conditions for creating a store, an error is sent and the ShopPreCreateEvent is not called (because the player cannot prepare to create a store at all).

**Comment by Baktus79** [comment]
OK I understand. Is there a way for me, through the API, to be able to stop this message from being sent to a specific player?

**Comment by Ghost-chu** [comment]
> OK I understand. Is there a way for me, through the API, to be able to stop this message from being sent to a specific player?

I recommend that you leave the translated text of the specified message as an empty string. This way QuickShop will skip it when sending this message.

**Comment by Ghost-chu** [comment]
> OK I understand. Is there a way for me, through the API, to be able to stop this message from being sent to a specific player?

https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/modules/localization#customize-translations

**Comment by Baktus79** [comment]
I did it through override. The message was stopped, but a blank line still appeared.

**Comment by Ghost-chu** [comment]
Blank lines should not be sent

**Comment by Baktus79** [comment]
Thanks for your help, I appreciate it :)
