### ISSUE TITLE
[BUG] Shops are removed from people without permission

### ISSUE THREAD

**Issue by Folas1337** [Ghost-chu/QuickShop-Hikari#1790]
### Description

Disabling the lock feature of the plugin and relying on another block protection plugin like Towny, it's possible for another player who doesn't have access to chunks to remove a shop by spam breaking the sign with an efficiency 5 diamond axe.

It even confirms in chat "Shop removed." as if QuickShop approved of the interaction while this should have never happened.

### Steps to reproduce

1. Install QuickShop
2. Install Towny
3. Create a town with '/town new testTown'
4. Change "shop.lock" to false in the QuickShop config.yml
5. Create a shop inside of your town
6. Get another player to join
7. Give them a diamond axe with Efficiency 5
8. This player shouldn't be able to break anything within the town chunk BUT for some reason if you keep spam breaking the sign of the shop, it'll break eventually

### Expected Behaviour

The shop sign should never break and the shop itself should also never be removed.

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FbXLzZPAr0U

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by BlvckBytes** [comment]
After having had an extensive look at this specific case, I noticed how the sign only played a secondary role in reproducing the unauthorized shop-removal. The quickest way to achieve this behavior is, to my current knowledge, as follows:

> Looks like it has something to do with the "Outsiders aren't allowed to Destroy"-message. Once that's received while trying to destroy the shop, the player can destroy it over and over again, until interacting with another block. While in this state, they seem to bypass the checks. The easiest way to achieve this seems to be to wait for a while since having received the last towny-message, and then sneak while destroying. There are other, more nuanced ways to achieve it too, though.

Since the message `<green>Shop removed.` is printed in chat, I located its corresponding config-key, namely `success-removed-shop`; once searching globally for `"success-removed-shop"`, the only occurrence was within `com.ghostchu.quickshop.listener.BlockListener#onBreak` - at line 90, on commit `0108ce6d48568e409c930950f6c1764b198f620e`. Notice how there's not a single check for whether the player has any right to destroy the shop within that event-handler, as it relies on external plugins having cancelled it beforehand, as it itself has the flag `ignoreCancelled` set to true, thereby not being invoked if the player could not actually, permanently, break that block.

While I very much do believe that the priority-queue of bukkit's event-handler is deterministic, meaning that it's established once on startup and executes in the same order each time, eliminating "race-conditions", `Towny` seems to have multiple handlers registered for different cases, like that one way to reproduce it I described above. Registering the handler within QuickShop-Hikari on priority `Normal` can cause it to be called before any protection-plugins had a chance to take action and cancel the event.

The fix is thus as simple as it is mind-boggling that nobody else yet ran into this issue: change the priority to `MONITOR`, as it always should've been, since this plugin only reads, and requires the latest state. I'll make sure to open a pull-request for this patch.
