### ISSUE TITLE
Not work with wildtools

### ISSUE THREAD

**Issue by Distolfix** [Ghost-chu/QuickShop-Hikari#962]
### Description

https://github.com/BG-Software-LLC/WildTools/issues/155

### Steps to reproduce

.

### Expected Behaviour

.

### Screenshots

.

### `/qs paste` URL

no

### Additional Context

Looks this github report

**Comment by Ghost-chu** [comment]
The following information must be provided, otherwise we cannot provide you with any assistance:

* You must update the QuickShop-Hikari to latest revision on Modrinth, for currently it's 4.2.2.10.
* You must update your server jar to latest minor revision like 1.18.2, 1.19.4 etc, not 1.18.1 or 1.19.3
* **`/qs paste`** is **absolutely** necessary, Paste contains important technical information about QuickShop-Hikari, but also basic information about other plugins installed on your server (e.g. version number), which is of great help to us.
